blank_issues_enabled: false
contact_links:
  - name: Feature Request (GitHub Discussion Beta)
    url: https://github.com/fluentmigrator/fluentmigrator/discussions/new
    about: Share ideas for new features
  - name: Ask a Question (GitHub Discussion Beta)
    url: https://github.com/fluentmigrator/fluentmigrator/discussions/new?discussions_q=category%3AHelp
    about: Ask the community for help
