#region License
//
// Copyright (c) 2019, Fluent Migrator Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#endregion

using FluentMigrator.Runner.Generators.Postgres;
using FluentMigrator.Runner.Generators.Postgres10;
using FluentMigrator.Runner.Processors.Postgres;
using FluentMigrator.Tests.Unit.Generators.Postgres;

using NUnit.Framework;

using Shouldly;

using System.Data;

namespace FluentMigrator.Tests.Unit.Generators.Postgres10
{
    [TestFixture]
    public class Postgres10GeneratorTests : PostgresGeneratorTests
    {
        protected new Postgres10Generator Generator;

        [SetUp]
        public new void Setup()
        {
            var quoter = new PostgresQuoter(new PostgresOptions());
            Generator = new Postgres10Generator(quoter);
        }

        [Test]
        public override void CanCreateAutoIncrementColumnForInt64()
        {
            var expression = GeneratorTestHelper.GetCreateTableWithAutoIncrementExpression();
            expression.Columns[0].Type = DbType.Int64;

            var result = Generator.Generate(expression);
            result.ShouldBe("CREATE TABLE \"public\".\"TestTable1\" (\"TestColumn1\" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, \"TestColumn2\" integer NOT NULL);");
        }
    }
}
