#region License
//
// Copyright (c) 2019, Fluent Migrator Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#endregion

using FluentMigrator.Runner.Generators.Postgres;
using FluentMigrator.Runner.Generators.Postgres10;
using FluentMigrator.Runner.Processors.Postgres;

using NUnit.Framework;

using Shouldly;

namespace FluentMigrator.Tests.Unit.Generators.Postgres10
{
    [TestFixture]
    public class Postgres10TableTests : Postgres.PostgresTableTests
    {
        protected new Postgres10Generator Generator;

        [SetUp]
        public new void Setup()
        {
            var quoter = new PostgresQuoter(new PostgresOptions());
            Generator = new Postgres10Generator(quoter);
        }

        [Test]
        public override void CanCreateTableWithIdentityWithCustomSchema()
        {
            var expression = GeneratorTestHelper.GetCreateTableWithAutoIncrementExpression();
            expression.SchemaName = "TestSchema";

            var result = Generator.Generate(expression);
            result.ShouldBe("CREATE TABLE \"TestSchema\".\"TestTable1\" (\"TestColumn1\" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, \"TestColumn2\" integer NOT NULL);");
        }

        [Test]
        public override void CanCreateTableWithIdentityWithDefaultSchema()
        {
            var expression = GeneratorTestHelper.GetCreateTableWithAutoIncrementExpression();

            var result = Generator.Generate(expression);
            result.ShouldBe("CREATE TABLE \"public\".\"TestTable1\" (\"TestColumn1\" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, \"TestColumn2\" integer NOT NULL);");
        }

        [Test]
        public void CanCreateTableWithIdentityByDefaultWithCustomSchema()
        {
            var expression = GeneratorTestHelper.GetCreateTableWithAutoIncrementExpression();
            expression.Columns[0].AdditionalFeatures.Add("PostgresIdentityGeneration", PostgresGenerationType.ByDefault);

            expression.SchemaName = "TestSchema";

            var result = Generator.Generate(expression);
            result.ShouldBe("CREATE TABLE \"TestSchema\".\"TestTable1\" (\"TestColumn1\" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, \"TestColumn2\" integer NOT NULL);");
        }

        [Test]
        public void CanCreateTableWithIdentityByDefaultWithDefaultSchema()
        {
            var expression = GeneratorTestHelper.GetCreateTableWithAutoIncrementExpression();
            expression.Columns[0].AdditionalFeatures.Add("PostgresIdentityGeneration", PostgresGenerationType.ByDefault);

            var result = Generator.Generate(expression);
            result.ShouldBe("CREATE TABLE \"public\".\"TestTable1\" (\"TestColumn1\" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, \"TestColumn2\" integer NOT NULL);");
        }

        [Test]
        public void CanCreateTableWithIdentityAlwaysWithCustomSchema()
        {
            var expression = GeneratorTestHelper.GetCreateTableWithAutoIncrementExpression();
            expression.Columns[0].AdditionalFeatures.Add("PostgresIdentityGeneration", PostgresGenerationType.Always);

            expression.SchemaName = "TestSchema";

            var result = Generator.Generate(expression);
            result.ShouldBe("CREATE TABLE \"TestSchema\".\"TestTable1\" (\"TestColumn1\" integer NOT NULL GENERATED ALWAYS AS IDENTITY, \"TestColumn2\" integer NOT NULL);");
        }

        [Test]
        public void CanCreateTableWithIdentityAlwaysWithDefaultSchema()
        {
            var expression = GeneratorTestHelper.GetCreateTableWithAutoIncrementExpression();
            expression.Columns[0].AdditionalFeatures.Add("PostgresIdentityGeneration", PostgresGenerationType.Always);

            var result = Generator.Generate(expression);
            result.ShouldBe("CREATE TABLE \"public\".\"TestTable1\" (\"TestColumn1\" integer NOT NULL GENERATED ALWAYS AS IDENTITY, \"TestColumn2\" integer NOT NULL);");
        }
    }
}
