using FluentMigrator.Model;

namespace FluentMigrator.Runner.Generators.Oracle
{
    internal class Oracle12CColumn : OracleColumn
    {
        /// <inheritdoc />
        public Oracle12CColumn(IQuoter quoter) : base(quoter)
        {
        }

        private static string GetIdentityString(ColumnDefinition column)
        {
            return "GENERATED BY DEFAULT AS IDENTITY"; // TODO Handle Generated type
        }

        /// <inheritdoc />
        protected override string FormatIdentity(ColumnDefinition column)
        {
            return column.IsIdentity ? GetIdentityString(column) : string.Empty;
        }

        /// <inheritdoc />
        protected override string FormatNullable(ColumnDefinition column)
        {
            //Creates always return Not Null unless is nullable is true
            if (column.ModificationType == ColumnModificationType.Create)
            {
                if (column.IsNullable.HasValue && column.IsNullable.Value || column.IsIdentity)
                {
                    return string.Empty;
                }
                else
                {
                    return "NOT NULL";
                }
            }

            //alter only returns "Not Null" if IsNullable is explicitly set
            if (column.IsNullable.HasValue)
            {
                return column.IsNullable.Value ? "NULL" : "NOT NULL";
            }
            else
            {
                return string.Empty;
            }
        }
    }
}
