//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentMigrator.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluentMigrator.Infrastructure.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column&apos;s name cannot be null or an empty string..
        /// </summary>
        public static string ColumnNameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ColumnNameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column names must be unique..
        /// </summary>
        public static string ColumnNamesMustBeUnique {
            get {
                return ResourceManager.GetString("ColumnNamesMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column does not have a type defined..
        /// </summary>
        public static string ColumnTypeMustBeDefined {
            get {
                return ResourceManager.GetString("ColumnTypeMustBeDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The constraint must have at least one column specified..
        /// </summary>
        public static string ConstraintMustHaveAtLeastOneColumn {
            get {
                return ResourceManager.GetString("ConstraintMustHaveAtLeastOneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default value cannot be null..
        /// </summary>
        public static string DefaultValueCannotBeNull {
            get {
                return ResourceManager.GetString("DefaultValueCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination schema&apos;s name cannot be null or an empty string..
        /// </summary>
        public static string DestinationSchemaCannotBeNull {
            get {
                return ResourceManager.GetString("DestinationSchemaCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expression.TableName must not be empty.
        /// </summary>
        public static string ExpressionTableNameMissing {
            get {
                return ResourceManager.GetString("ExpressionTableNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name not specified, ensure you have appended the OnTable extension. Format should be Delete.ForeignKey(KeyName).OnTable(TableName).
        /// </summary>
        public static string ExpressionTableNameMissingWithHints {
            get {
                return ResourceManager.GetString("ExpressionTableNameMissingWithHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The foreign key column names must be unique..
        /// </summary>
        public static string ForeignKeyColumnNamesMustBeUnique {
            get {
                return ResourceManager.GetString("ForeignKeyColumnNamesMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The foreign key columns&apos; count must match the primary key columns&apos; count..
        /// </summary>
        public static string ForeignKeyColumnsCountMustMatchPrimaryKeyColumnsCount {
            get {
                return ResourceManager.GetString("ForeignKeyColumnsCountMustMatchPrimaryKeyColumnsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The foreign key must have one or more foreign columns..
        /// </summary>
        public static string ForeignKeyMustHaveOneOrMoreForeignColumns {
            get {
                return ResourceManager.GetString("ForeignKeyMustHaveOneOrMoreForeignColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The foreign key must have one or more primary columns..
        /// </summary>
        public static string ForeignKeyMustHaveOneOrMorePrimaryColumns {
            get {
                return ResourceManager.GetString("ForeignKeyMustHaveOneOrMorePrimaryColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The foreign key must not have a column name be null or an empty string..
        /// </summary>
        public static string ForeignKeyMustNotHaveColumnNameBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ForeignKeyMustNotHaveColumnNameBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The foreign key&apos;s name cannot be null or an empty string..
        /// </summary>
        public static string ForeignKeyNameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ForeignKeyNameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The foreign table name cannot be null or empty..
        /// </summary>
        public static string ForeignTableNameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ForeignTableNameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index include column&apos;s name must not be null or an empty string..
        /// </summary>
        public static string IndexIncludeColumnNameMustNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("IndexIncludeColumnNameMustNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index must have one or more columns..
        /// </summary>
        public static string IndexMustHaveOneOrMoreColumns {
            get {
                return ResourceManager.GetString("IndexMustHaveOneOrMoreColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index&apos;s name cannot be null or an empty string..
        /// </summary>
        public static string IndexNameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("IndexNameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} method must be called on an object that implements {1}..
        /// </summary>
        public static string MethodXMustBeCalledOnObjectImplementingY {
            get {
                return ResourceManager.GetString("MethodXMustBeCalledOnObjectImplementingY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new column name cannot be null or empty..
        /// </summary>
        public static string NewColumnNameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("NewColumnNameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new table name cannot be null or empty..
        /// </summary>
        public static string NewTableNameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("NewTableNameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old column name cannot be null or empty..
        /// </summary>
        public static string OldColumnNameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("OldColumnNameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old table name cannot be null or empty..
        /// </summary>
        public static string OldTableNameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("OldTableNameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation to be performed using the database connection cannot be null..
        /// </summary>
        public static string OperationCannotBeNull {
            get {
                return ResourceManager.GetString("OperationCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key column name referenced by the foreign key must not be null or an empty string..
        /// </summary>
        public static string PrimaryKeyColumnNameReferencedByForeignKeyMustNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("PrimaryKeyColumnNameReferencedByForeignKeyMustNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key column names must be unique..
        /// </summary>
        public static string PrimaryKeyColumnNamesMustBeUnique {
            get {
                return ResourceManager.GetString("PrimaryKeyColumnNamesMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary table name cannot be null or empty..
        /// </summary>
        public static string PrimaryTableNameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("PrimaryTableNameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema&apos;s name cannot be null or an empty string..
        /// </summary>
        public static string SchemaNameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("SchemaNameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence&apos;s name cannot be null or an empty string..
        /// </summary>
        public static string SequenceNameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("SequenceNameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sql script cannot be null or an empty string..
        /// </summary>
        public static string SqlScriptCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("SqlScriptCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sql statement cannot be null or an empty string..
        /// </summary>
        public static string SqlStatementCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("SqlStatementCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table&apos;s name cannot be null or an empty string..
        /// </summary>
        public static string TableNameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("TableNameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update statement specifies both a .Where() condition and that .AllRows() should be targeted. Specify one or the other, but not both..
        /// </summary>
        public static string UpdateDataExpressionMustNotSpecifyBothWhereClauseAndAllRows {
            get {
                return ResourceManager.GetString("UpdateDataExpressionMustNotSpecifyBothWhereClauseAndAllRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update statement is missing a condition. Specify one by calling .Where() or target all rows by calling .AllRows()..
        /// </summary>
        public static string UpdateDataExpressionMustSpecifyWhereClauseOrAllRows {
            get {
                return ResourceManager.GetString("UpdateDataExpressionMustSpecifyWhereClauseOrAllRows", resourceCulture);
            }
        }
    }
}
