
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18449
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyProductAttribute("FluentMigrator")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright - Sean Chambers 2008-2010")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("debug")]
[assembly: System.CLSCompliantAttribute(true)]

