name: Trigger Azure Pipelines on pull request labeled 'needs:ci-build'

on:
  pull_request_target:
    types: [ labeled ]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# Set up the following secrets in your repository:
#   AZURE_CREDENTIALS, REGISTRY_USERNAME, REGISTRY_PASSWORD, AZURE_DEVOPS_TOKEN
# 2. Change these variables for your configuration:
jobs:
    
  trigger-azure-pipelines:
    if: ${{ github.event.label.name == 'needs:ci-build' }}
    runs-on: ubuntu-latest
    steps:
    - name: 'Trigger an Azure Pipeline to force a CI build'
      uses: Azure/pipelines@releases/v1
      with:
        # Fullyqualified URL to the Azure DevOps organization along with project name(eg, https://dev.azure.com/organization/project-name or https://server.example.com:8080/tfs/DefaultCollection/project-name)
        azure-devops-project-url: 'https://dev.azure.com/FluentMigrator/FluentMigrator'
        # Name of the Azure Pipline to be triggered
        azure-pipeline-name: 'fluentmigrator CI for PRs'
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
        azure-pipeline-variables: '{ "Build.SourceVersion": "${{ github.event.pull_request.head.sha }}" }'
